### PR TITLE
[semver:patch] Initialize AWS_CLI_VER_STRING

### PR DESCRIPTION
**Pull request by brandon-leapyear**
### Checklist

- [ ] All new jobs, commands, executors, parameters have descriptions
- [ ] Examples have been added for any significant new features
- [ ] README has been updated, if necessary

### Motivation, issues

Resolves https://github.com/CircleCI-Public/aws-cli-orb/issues/76

### CODE REVIEW

**Review by gmemstr — APPROVED** [review]

**Comment by nanish94** [comment]
brandon-leapyear:patch-2

**Comment by nanish94** [comment]
brandon-leapyear:patch-2 main

**Comment by nanish94** [comment]
brandon-leapyear:patch-2 comment

**Comment by nanish94** [comment]
https://github.com/CircleCI-Public/aws-cli-orb/commit/5240e11230c9548d6bd7ee61fef7ff87ca4fb3af

**Comment by nanish94** [comment]
https://github.com/CircleCI-Public/aws-cli-orb/commit/5240e11230c9548d6bd7ee61fef7ff87ca4fb3af comment

**Review by nanish94 — COMMENTED** [review]
src/scripts/install.sh comment

**Comment by nanish94** [comment]
src/scripts/install.sh main

**Comment by brandon-leapyear** [comment]
@nanish94 what are you trying to do? Please stop spamming this PR with comments

**Review by nanish94 — COMMENTED** [review]
leave a comment

**Comment by nanish94** [comment]
comment

**Pull request merged**
