### PR TITLE
Fix orb badge

### PR DESCRIPTION
**Pull request by brandon-leapyear**
The orb version in the README is incorrect

### CODE REVIEW

**Review by adamdmharvey — APPROVED** [review]

**Review by KyleTryon — APPROVED** [review]
Much appreciated

**Comment by brivu** [comment]
Hey @brandon-leapyear, 

I've fixed this in the newest major update. Thanks for contributing! 

Best, 
Brian

**Comment by brandon-leapyear** [comment]
Did you fix this? I still see `slack.svg` in `README.md` in master

**Comment by adamdmharvey** [comment]
@brandon-leapyear See related PR linked above which is in "Draft"; so not yet.

**Pull request closed without merging**
